### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by malukenho** [codelicia/depreday#1]

**Comment by malukenho** [comment]
@all-contributors please add @malukenho for maintenance and code

**Comment by malukenho** [comment]
@all-contributors please add @batusa for review

**Comment by EHER** [comment]
@all-contributors please add @EHER for ideas

**Comment by malukenho** [comment]
@all-contributors please add @peter279k  for code

**Comment by EHER** [comment]
Seems done to me.

all-contributors can be called on any issue (maybe on PRs too).

If needed we can re-open it.
